// Conversaciones de rodaje para practicar las expresiones del PDF. Tú eres uno de los personajes.
// Líneas: ['narr', 'lo que pasa (en español)'] · ['personaje', 'inglés', 'español']
// Te toca hablar:
//   { task: 'choose', say: 'qué tienes que decir', options: [['la buena', 'su traducción'], ['una mala', 'por qué está mal'], …] }
//   { task: 'order', say: '…', en: 'la frase', es: 'su traducción' }               (ordenar las palabras)
//      (con alt: ['otro orden'] si hay otro orden que también está bien)
//   { task: 'gap', say: '…', en: 'frase con la [palabra] que falta', es: '…' }       (completar)
const CONVOS = [
  {
    id: 'reunion', icon: '📋', title: 'Reunión de producción', you: 'Coordinador/a de producción',
    desc: 'Cerráis el calendario del cortometraje con la productora y el director.',
    cast: {
      emma: { name: 'Emma', role: 'Productora', avatar: '👩‍💼', pitch: 1.15 },
      leo: { name: 'Leo', role: 'Director', avatar: '🧔', pitch: 0.85 },
      sara: { name: 'Sara', role: 'Ayudante de dirección', avatar: '👩‍🦰', pitch: 1.25 },
    },
    lines: [
      ['narr', 'Lunes, 9:00. Oficina de producción. Quedan tres semanas para rodar el cortometraje.'],
      ['emma', "Good morning, everyone. Let's get started.", 'Buenos días a todos. Empecemos.'],
      ['emma', "First, let's go over the agenda. Sara, what's the current status?", 'Primero, repasemos el orden del día. Sara, ¿cuál es el estado actual?'],
      ['sara', "We're running behind schedule. Two locations aren't confirmed yet.", 'Vamos retrasados respecto al calendario. Todavía no están confirmadas dos localizaciones.'],
      { task: 'choose', say: 'Pregunta cuál es la fecha límite.', options: [
        ["What's the deadline?", '¿Cuál es la fecha límite?'],
        ["What's the dead line time?", '«Deadline» es una sola palabra y no lleva «time».'],
        ['Which is the limit date?', 'Es una traducción palabra por palabra de «fecha límite». En inglés se dice «deadline».'],
      ] },
      ['emma', "We need to finalize the schedule by Friday. We're working to a tight deadline.", 'Tenemos que cerrar el calendario antes del viernes. Trabajamos con un plazo muy ajustado.'],
      ['leo', "Then we need to make a few changes. Let's go over the details.", 'Entonces tenemos que hacer algunos cambios. Vamos a repasar los detalles.'],
      { task: 'order', say: 'Di que hay que ajustarse al calendario.', en: 'We need to stick to the schedule.', es: 'Tenemos que ajustarnos al calendario.' },
      ['leo', 'I see your point. But the night scene needs more time.', 'Entiendo tu punto de vista. Pero la escena nocturna necesita más tiempo.'],
      ['emma', "That's a good point. We need to discuss this further.", 'Es un buen punto. Tenemos que hablar más sobre esto.'],
      { task: 'choose', say: 'No has entendido bien lo de la escena nocturna: pide que lo aclaren.', options: [
        ['Could you clarify that?', '¿Podrías aclararlo?'],
        ['Could you clear that?', '«Clear» es despejar o limpiar. «Aclarar» se dice «clarify».'],
        ['Can you explain me that?', 'En inglés no se dice «explain me»: sería «explain it to me». Lo más educado aquí es «Could you clarify that?».'],
      ] },
      ['leo', 'Sure. We need two more hours on set for the lighting.', 'Claro. Necesitamos dos horas más en el plató para la iluminación.'],
      { task: 'gap', say: 'Di que tomas nota.', en: "I'll make a [note] of that.", es: 'Tomo nota de ello.' },
      ['emma', "Great. Let's move on to the next item: the budget.", 'Genial. Pasemos al siguiente punto: el presupuesto.'],
      ['sara', "I'll check and let you know before Friday.", 'Lo comprobaré y te lo comunicaré antes del viernes.'],
      { task: 'choose', say: 'Pide a Sara que te mantenga informado/a.', options: [
        ['Keep me updated.', 'Mantenme informado/a.'],
        ['Keep me update.', 'Después de «keep me» va el participio: «updated».'],
        ['Maintain me informed.', 'Es una traducción literal de «mantenme informado». Se dice «Keep me updated» (o «Keep me posted»).'],
      ] },
      ['sara', "Of course. I'll keep you posted.", 'Claro. Te mantendré informado/a.'],
      ['emma', 'Are we all on the same page? Perfect. Thanks, everyone!', '¿Estamos todos de acuerdo? Perfecto. ¡Gracias a todos!'],
    ],
  },
  {
    id: 'rodaje', icon: '🎬', title: 'Primer día de rodaje', you: 'Ayudante de dirección',
    desc: 'Pides silencio, das las órdenes de rodaje y repetís la toma.',
    cast: {
      leo: { name: 'Leo', role: 'Director', avatar: '🧔', pitch: 0.85 },
      nora: { name: 'Nora', role: 'Actriz', avatar: '👩‍🎤', pitch: 1.2 },
      max: { name: 'Max', role: 'Operador de cámara', avatar: '👨‍🦱', pitch: 0.95 },
      ana: { name: 'Ana', role: 'Técnica de sonido', avatar: '👩‍🔧', pitch: 1.1 },
    },
    lines: [
      ['narr', 'Primer día de rodaje. Escena 4: interior de una cafetería. Todo el equipo está en su sitio.'],
      ['leo', 'Are we ready to shoot?', '¿Estamos preparados para rodar?'],
      { task: 'choose', say: 'Pide silencio en el plató.', options: [
        ['Quiet on set, please.', 'Silencio en el plató, por favor.'],
        ['Silence in the set, please.', 'Es una traducción literal. En un rodaje se dice «Quiet on set» (con «on»).'],
        ['Shut up on set, please.', '«Shut up» es muy maleducado (¡cállate!). La fórmula profesional es «Quiet on set, please».'],
      ] },
      ['max', 'Camera ready.', 'Cámara preparada.'],
      ['ana', 'Sound ready.', 'Sonido preparado.'],
      { task: 'choose', say: 'Avisa a todo el equipo de que estén preparados.', options: [
        ['Stand by.', 'Preparados / en espera.'],
        ['Stand up.', '«Stand up» es ponerse de pie. «Preparados» se dice «Stand by».'],
        ['Be prepare.', 'Sería «Be prepared», pero en un rodaje se dice «Stand by».'],
      ] },
      ['max', 'Rolling.', 'Grabando.'],
      ['leo', 'And... action!', 'Y... ¡acción!'],
      ['narr', 'Nora dice su texto, pero al final tropieza con una silla.'],
      ['leo', 'Cut! Nora, are you OK?', '¡Corten! Nora, ¿estás bien?'],
      ['nora', 'Yes, sorry! Can we go again?', 'Sí, ¡perdón! ¿Podemos repetir?'],
      { task: 'order', say: 'Propón hacer otra toma.', en: "Let's do another take.", es: 'Hagamos otra toma.' },
      ['leo', 'Yes. Back to one, everybody!', 'Sí. ¡Volvemos al principio, todos!'],
      { task: 'choose', say: 'Pide a Nora que se mueva un poco a la izquierda.', options: [
        ['Move slightly to the left.', 'Muévete ligeramente a la izquierda.'],
        ['Move slightly to the leave.', '«Leave» es irse. Izquierda se dice «left».'],
        ['Move slightly at the left.', 'Para una dirección se usa «to»: «to the left».'],
      ] },
      ['nora', 'Here?', '¿Aquí?'],
      { task: 'gap', say: 'Dile que se quede justo ahí, en esa posición.', en: '[Hold] that position.', es: 'Mantén esa posición.' },
      ['narr', 'Segunda toma. Esta vez todo sale perfecto.'],
      ['leo', 'Cut! That was a good take.', '¡Corten! Ha sido una buena toma.'],
      { task: 'choose', say: 'Propón hacer una más, por seguridad.', options: [
        ["Let's do one more.", 'Hagamos una más.'],
        ["Let's make one more.", 'Con las tomas se usa «do»: «Let\'s do one more» o «Let\'s do another take».'],
        ['We do one more?', 'Para proponer algo se usa «Let\'s…»: «Let\'s do one more».'],
      ] },
      ['leo', 'Good idea. Reset, please.', 'Buena idea. Volvemos a la posición inicial, por favor.'],
    ],
  },
  {
    id: 'camara', icon: '🎥', title: 'Con el equipo de cámara', you: 'Operador/a de cámara',
    desc: 'Una entrevista en exteriores: planos, encuadre y foco.',
    cast: {
      mike: { name: 'Mike', role: 'Director de fotografía', avatar: '🧑‍🦲', pitch: 0.8 },
      lucia: { name: 'Lucía', role: 'Foquista', avatar: '👩', pitch: 1.2 },
      leo: { name: 'Leo', role: 'Director', avatar: '🧔', pitch: 0.85 },
    },
    lines: [
      ['narr', 'Escena 7: una entrevista en un jardín. Tú llevas la cámara y Mike es el director de fotografía.'],
      ['mike', 'Get the shot ready, please. We start in five minutes.', 'Prepara el plano, por favor. Empezamos en cinco minutos.'],
      { task: 'choose', say: 'Pregunta si empezáis con un plano general.', options: [
        ['Shall we start with a wide shot?', '¿Empezamos con un plano general?'],
        ['Shall we start with a general plane?', '«Plane» es un avión 😅. Plano general se dice «wide shot» (o «long shot»).'],
        ['Shall we start with a big shot?', 'No es un término técnico. Plano general = «wide shot».'],
      ] },
      ['mike', "Yes. Let's get a wide shot first, and then we'll go tighter.", 'Sí. Primero hagamos un plano general y luego cerraremos el plano.'],
      ['lucia', 'Be careful, the subject moves a lot.', 'Ten cuidado, el sujeto se mueve mucho.'],
      { task: 'order', say: 'Tranquilízala: di que mantendrás al sujeto en el encuadre.', en: "I'll keep the subject in frame.", es: 'Mantendré al sujeto en el encuadre.' },
      ['mike', 'Good. Now go wider. I want to see the garden.', 'Bien. Ahora abre el plano. Quiero ver el jardín.'],
      ['narr', 'Después del plano general, el director quiere más detalle.'],
      ['leo', "Let's get a close-up of her hands.", 'Hagamos un primer plano de sus manos.'],
      { task: 'choose', say: 'Pide a Lucía que compruebe el enfoque.', options: [
        ['Check the focus, please.', 'Comprueba el enfoque, por favor.'],
        ['Check the approach, please.', '«Approach» es enfoque en el sentido de «manera de abordar algo». El enfoque de la cámara es «focus».'],
        ['Revise the focus, please.', '«Revise» es repasar un texto para corregirlo. Para la cámara se dice «check».'],
      ] },
      ['lucia', "Focus is good. I'll pull focus when she looks up.", 'El foco está bien. Haré el cambio de foco cuando levante la vista.'],
      ['leo', "Hmm, I can't see her face very well.", 'Mmm, no le veo bien la cara.'],
      { task: 'gap', say: 'Propón cerrar más el plano.', en: "Let's go [tighter], then.", es: 'Entonces cerremos el plano.' },
      ['leo', 'Great. Hold the shot!', '¡Genial! ¡Mantén el plano!'],
      ['narr', 'Al revisar la toma, al director no le convence la posición de la cámara.'],
      { task: 'choose', say: 'Propón otro ángulo.', options: [
        ['We need another angle.', 'Necesitamos otro ángulo.'],
        ['We need other angle.', 'Con un sustantivo en singular se dice «another» (otro), no «other».'],
        ['We need another corner.', '«Corner» es una esquina. El ángulo de cámara es «angle».'],
      ] },
      ['mike', "Agreed. Let's pan left and follow the action.", 'De acuerdo. Hagamos una panorámica a la izquierda y sigamos la acción.'],
    ],
  },
  {
    id: 'sonido', icon: '🎙️', title: 'Sonido directo', you: 'Técnico/a de sonido directo',
    desc: 'Ruido de fondo, saturación y tono de sala en un rodaje en la calle.',
    cast: {
      ana: { name: 'Ana', role: 'Microfonista', avatar: '👩‍🔧', pitch: 1.1 },
      leo: { name: 'Leo', role: 'Director', avatar: '🧔', pitch: 0.85 },
    },
    lines: [
      ['narr', 'Rodaje en una calle del centro. Tú eres el técnico de sonido directo y llevas los auriculares.'],
      ['leo', 'Sound ready?', '¿Sonido preparado?'],
      { task: 'choose', say: 'Antes de grabar, pide a Ana que compruebe los niveles de sonido.', options: [
        ['Check the sound levels, please.', 'Comprueba los niveles de sonido, por favor.'],
        ['Check the sound nivels, please.', '«Nivel» en inglés es «level» (en plural, «levels»).'],
        ['Check the sound volumes level, please.', 'No tiene sentido. Se dice «Check the sound levels».'],
      ] },
      ['ana', "Levels are fine. But we're getting some background noise.", 'Los niveles están bien. Pero estamos captando algo de ruido de fondo.'],
      ['leo', 'Where is it coming from?', '¿De dónde viene?'],
      ['ana', "There's a bar across the street. There's too much noise.", 'Hay un bar al otro lado de la calle. Hay demasiado ruido.'],
      { task: 'order', say: 'Pide otra toma por culpa del sonido.', en: 'We need another take for sound.', es: 'Necesitamos otra toma para sonido.' },
      ['narr', 'En la toma anterior, la pértiga se veía en la parte de arriba de la imagen.'],
      { task: 'choose', say: 'Pide a Ana que deje el micro fuera de plano.', options: [
        ['Keep the microphone out of shot.', 'Mantén el micrófono fuera de plano.'],
        ['Keep the microphone out of plane.', '«Plane» es un avión. «Fuera de plano» se dice «out of shot».'],
        ['Keep the microphone off the picture frame.', '«Picture frame» es el marco de un cuadro. Se dice «out of shot».'],
      ] },
      ['ana', "Sorry! I'll be careful.", '¡Perdón! Tendré cuidado.'],
      ['narr', 'Grabáis otra toma. El actor grita una frase y el medidor se pone en rojo.'],
      { task: 'gap', say: 'Avisa de que hay saturación.', en: "We're getting [clipping].", es: 'Estamos teniendo saturación.' },
      ['leo', 'Can we fix it?', '¿Podemos arreglarlo?'],
      { task: 'choose', say: 'Di que bajarás la ganancia y pide que vigilen los niveles.', options: [
        ["I'll reduce the gain. Watch the levels.", 'Bajaré la ganancia. Vigila los niveles.'],
        ["I'll reduce the gain. Look the levels.", '«Look» necesita «at» («look at»). Para controlar algo se usa «watch»: «Watch the levels».'],
        ["I'll reduce the win. Watch the levels.", '«Win» es ganar 😅. La ganancia de audio es «gain».'],
      ] },
      ['narr', 'Última toma. Esta vez todo suena limpio.'],
      ['ana', 'The signal is clean.', 'La señal está limpia.'],
      { task: 'order', say: 'Confirma al director que el sonido está bien.', en: 'We have good sound.', es: 'Tenemos buen sonido.' },
      ['leo', 'Great! Before we move, we need room tone.', '¡Genial! Antes de cambiar de sitio, necesitamos grabar tono de sala.'],
      ['narr', 'Todo el equipo se queda en silencio treinta segundos mientras grabas el tono de sala.'],
    ],
  },
  {
    id: 'luz', icon: '💡', title: 'Iluminación del plató', you: 'Jefe/a de eléctricos (gaffer)',
    desc: 'Una escena nocturna: luz principal, relleno, intensidad y temperatura de color.',
    cast: {
      mike: { name: 'Mike', role: 'Director de fotografía', avatar: '🧑‍🦲', pitch: 0.8 },
      pablo: { name: 'Pablo', role: 'Técnico de iluminación', avatar: '👨‍🔧', pitch: 1 },
    },
    lines: [
      ['narr', 'Plató, 8:00. Preparáis la luz de una escena nocturna en un dormitorio.'],
      ['mike', 'Check the lighting before the actors arrive.', 'Comprueba la iluminación antes de que lleguen los actores.'],
      ['mike', 'The subject is underexposed. Her face is too dark.', 'El sujeto está subexpuesto. Tiene la cara demasiado oscura.'],
      { task: 'choose', say: 'Pide a Pablo que ajuste la luz principal.', options: [
        ['Adjust the key light.', 'Ajusta la luz principal.'],
        ['Adjust the light key.', 'En inglés el orden es «key light»: la palabra que describe va delante.'],
        ['Fit the key light.', '«Fit» es encajar o quedar bien (como la ropa). Para regular una luz se dice «adjust».'],
      ] },
      ['pablo', 'Done. Is it better now?', 'Hecho. ¿Está mejor ahora?'],
      ['mike', 'Better, but there are hard shadows under her eyes.', 'Mejor, pero hay sombras duras debajo de sus ojos.'],
      { task: 'order', say: 'Pide que añadan luz de relleno.', en: 'Add some fill light.', es: 'Añade algo de luz de relleno.' },
      ['pablo', 'Should I move the light?', '¿Muevo la luz?'],
      { task: 'choose', say: 'Dile que acerque la luz.', options: [
        ['Move the light closer.', 'Acerca la luz.'],
        ['Move the light more close.', 'El comparativo de «close» es «closer».'],
        ['Approach the light.', '«Approach» es acercarte tú a algo. Para acercar la luz se dice «Move the light closer».'],
      ] },
      ['mike', "Good. Now it's a bit too bright.", 'Bien. Ahora hay demasiada luz.'],
      { task: 'gap', say: 'Pide que bajen la intensidad.', en: '[Reduce] the intensity.', es: 'Reduce la intensidad.' },
      ['pablo', "What about the window? There's daylight coming in.", '¿Y la ventana? Está entrando luz del día.'],
      { task: 'choose', say: 'Pide que comprueben la temperatura de color.', options: [
        ['Check the colour temperature.', 'Comprueba la temperatura de color.'],
        ['Check the temperature of colour.', 'Se entiende, pero el término técnico es «colour temperature» (sin «of»).'],
        ['Check the colour heat.', '«Heat» es calor. El término es «colour temperature».'],
      ] },
      ['mike', 'We need less light from the window. Pablo, put a flag there.', 'Necesitamos menos luz de la ventana. Pablo, pon una bandera ahí.'],
      ['narr', 'Diez minutos después, el director de fotografía mira el monitor.'],
      { task: 'order', say: 'Di que la iluminación tiene buen aspecto.', en: 'The lighting looks good.', es: 'La iluminación tiene buen aspecto.' },
      ['mike', 'Agreed. Great job, team!', 'De acuerdo. ¡Buen trabajo, equipo!'],
    ],
  },
  {
    id: 'localizacion', icon: '📍', title: 'Buscando localización', you: 'Responsable de localizaciones',
    desc: 'Una nave industrial: disponibilidad, permisos, aparcamiento y horarios.',
    cast: {
      emma: { name: 'Emma', role: 'Productora', avatar: '👩‍💼', pitch: 1.15 },
      grant: { name: 'Sr. Grant', role: 'Dueño de la nave', avatar: '👴', pitch: 0.75, rate: 0.85 },
    },
    lines: [
      ['narr', 'Para el final del corto necesitáis una nave industrial. La productora te llama.'],
      ['emma', 'We need to scout the location this week. Is that possible?', 'Tenemos que visitar la localización esta semana. ¿Es posible?'],
      { task: 'choose', say: 'Dile que primero tienes que comprobar si la localización está disponible.', options: [
        ['First I need to check if the location is available.', 'Primero tengo que comprobar si la localización está disponible.'],
        ['First I need to check if the localization is available.', '«Localization» es adaptar un producto a otro país. Un lugar de rodaje es «location».'],
        ['First I need to check if the location is disposable.', '«Disposable» significa «desechable» 😅. Disponible es «available».'],
      ] },
      ['narr', 'Llamas al dueño de la nave, el señor Grant.'],
      ['grant', 'Hello? Yes, the warehouse is free next week.', '¿Diga? Sí, la nave está libre la semana que viene.'],
      { task: 'order', say: 'Pregunta si la localización está disponible el lunes.', en: 'Is the location available on Monday?', es: '¿Está disponible la localización el lunes?' },
      ['grant', 'Yes, it is. You can come and see it tomorrow.', 'Sí. Podéis venir a verla mañana.'],
      ['narr', 'Al día siguiente, en la nave.'],
      ['emma', "It's perfect! But are we allowed to film here?", '¡Es perfecta! ¿Pero nos dejan rodar aquí?'],
      { task: 'choose', say: 'Tranquiliza a Emma: tenéis permiso para rodar aquí.', options: [
        ['We have permission to shoot here.', 'Tenemos permiso para rodar aquí.'],
        ['We have permit to shoot here.', '«A permit» es el documento (un permiso) y necesita «a». Aquí se dice «We have permission».'],
        ['We have permission for shoot here.', 'Después de «permission» va «to» + verbo: «permission to shoot».'],
      ] },
      ['grant', 'Yes, I signed the location release yesterday.', 'Sí, firmé la autorización de localización ayer.'],
      ['emma', 'Great. Where is the crew parking?', 'Genial. ¿Dónde aparca el equipo?'],
      ['grant', "There's a big car park behind the building.", 'Hay un aparcamiento grande detrás del edificio.'],
      { task: 'gap', say: 'Pregunta dónde se entrega el equipo.', en: 'Where is the equipment being [delivered]?', es: '¿Dónde se entrega el equipo?' },
      ['grant', "At the back door. It's easier for the trucks.", 'En la puerta de atrás. Es más fácil para los camiones.'],
      ['emma', "Perfect. What's the call time on Monday?", 'Perfecto. ¿A qué hora es la convocatoria el lunes?'],
      { task: 'choose', say: 'Responde que la convocatoria es a las siete.', options: [
        ['Call time is at seven.', 'La convocatoria es a las siete.'],
        ['Call time is in seven.', 'Para decir la hora se usa «at»: «at seven».'],
        ['The call hour is at seven.', 'En un rodaje se dice «call time» (hora de convocatoria).'],
      ] },
      ['emma', 'And what time do we wrap?', '¿Y a qué hora terminamos el rodaje?'],
      { task: 'order', say: 'Responde que termináis a las ocho de la tarde.', en: 'We wrap at eight in the evening.', es: 'Terminamos el rodaje a las ocho de la tarde.' },
      ['narr', 'El lunes, a las ocho de la tarde…'],
      ['emma', "That's it! We're wrapping for today. Thank you, Mr Grant!", '¡Listo! Terminamos el rodaje por hoy. ¡Gracias, señor Grant!'],
    ],
  },
  {
    id: 'directo', icon: '🔴', title: '¡Estamos en directo!', you: 'Regidor/a de plató',
    desc: 'Un programa de televisión en directo: cámaras, señales y escaleta.',
    cast: {
      julia: { name: 'Julia', role: 'Realizadora (en el control)', avatar: '👩‍💻', pitch: 1.1 },
      tom: { name: 'Tom', role: 'Presentador', avatar: '🧑‍💼', pitch: 0.9 },
    },
    lines: [
      ['narr', 'Programa de televisión en directo. Tú eres el regidor del plató y hablas por el intercom con Julia, la realizadora.'],
      ['julia', 'One minute to air. Are we ready?', 'Un minuto para salir al aire. ¿Estamos listos?'],
      { task: 'choose', say: 'Confirma que todo está listo.', options: [
        ["We're all set.", 'Está todo listo.'],
        ["We're all sit.", '«Sit» es sentarse. «Está todo listo» se dice «We\'re all set».'],
        ['We are all ready set go.', 'Eso parece la salida de una carrera 😅. Se dice «We\'re all set».'],
      ] },
      ['julia', "Great. We're going live in ten seconds.", 'Genial. Vamos a entrar en directo en diez segundos.'],
      { task: 'order', say: 'Avisa a la cámara uno de que esté preparada.', en: 'Stand by camera one.', alt: ['Camera one, stand by.'], es: 'Cámara uno, preparada.' },
      ['julia', 'Five, four, three...', 'Cinco, cuatro, tres…'],
      { task: 'choose', say: 'Dale paso al presentador: ya está en antena.', options: [
        ["You're on!", '¡Estás en antena!'],
        ["You're in!", '«You\'re in» es «estás dentro» (de un grupo o un plan). En directo se dice «You\'re on».'],
        ["You're live on!", 'Se dice «You\'re on» o «You\'re live», pero no las dos juntas.'],
      ] },
      ['tom', 'Good evening and welcome to the show!', '¡Buenas noches y bienvenidos al programa!'],
      ['narr', 'Tom presenta a su invitada. Julia habla por el intercom.'],
      ['julia', "Take camera two. Camera two, you're live.", 'Pasamos a cámara dos. Cámara dos, estás en directo.'],
      ['tom', "What's next?", '¿Qué viene ahora?'],
      { task: 'gap', say: 'Recuérdale que siga la escaleta.', en: 'Follow the [running] order.', es: 'Sigue la escaleta.' },
      ['julia', 'Thirty seconds to the break. Ready for the next cue.', 'Treinta segundos para la pausa. Preparados para la siguiente señal.'],
      { task: 'choose', say: 'Dile a Tom que espere a tu señal.', options: [
        ['On my cue.', 'A mi señal.'],
        ['On my queue.', '«Queue» se pronuncia igual, pero es una cola de gente. La señal es «cue».'],
        ['In my signal.', 'Se dice «on my cue».'],
      ] },
      ['narr', 'Haces la señal con la mano. Tom termina su frase.'],
      ['julia', 'Go to commercial.', 'Vamos a publicidad.'],
      { task: 'order', say: 'Dile a Tom que ya no está en antena y que volvéis en dos minutos.', en: "You're off. We're back in two minutes.", es: 'Ya no estás en antena. Volvemos en dos minutos.' },
      ['tom', 'Thanks! Everything is under control.', '¡Gracias! Todo está bajo control.'],
      ['julia', 'Great work, everyone. Back to the studio in two minutes!', 'Buen trabajo, todos. ¡Volvemos al estudio en dos minutos!'],
    ],
  },
  {
    id: 'montaje', icon: '🎞️', title: 'Sala de montaje', you: 'Montador/a',
    desc: 'Elegís tomas, transiciones, color y exportáis la versión final.',
    cast: {
      leo: { name: 'Leo', role: 'Director', avatar: '🧔', pitch: 0.85 },
    },
    lines: [
      ['narr', 'Una semana después del rodaje. Estás en la sala de montaje con el director.'],
      ['leo', "Hi! Let's review the footage from Tuesday.", '¡Hola! Vamos a revisar el material grabado del martes.'],
      { task: 'choose', say: 'Pregúntale qué toma prefiere para la escena cuatro.', options: [
        ['Which take do you prefer for scene four?', '¿Qué toma prefieres para la escena cuatro?'],
        ['Which catch do you prefer for scene four?', '«Catch» es atrapar o una captura. Una toma es «take».'],
        ['Which take you prefer for scene four?', 'En las preguntas falta el auxiliar «do»: «Which take do you prefer…?».'],
      ] },
      ['leo', "Keep this take. It's the best one.", 'Conserva esta toma. Es la mejor.'],
      ['leo', 'But the ending is too long. Cut this shot.', 'Pero el final es demasiado largo. Corta este plano.'],
      { task: 'order', say: 'Propón usar la toma anterior.', en: 'Shall we use the previous take?', es: '¿Usamos la toma anterior?' },
      ['leo', 'Yes, good idea. And add a transition here.', 'Sí, buena idea. Y añade una transición aquí.'],
      { task: 'choose', say: 'Propón un fundido encadenado.', options: [
        ['How about a dissolve?', '¿Qué tal un fundido encadenado?'],
        ['How about a melted?', '«Melted» significa «derretido» 😅. Fundido encadenado se dice «dissolve».'],
        ['How about a fade chained?', 'Es una traducción palabra por palabra. Se dice «dissolve».'],
      ] },
      ['leo', 'Perfect. Hmm, this shot looks too blue.', 'Perfecto. Mmm, este plano se ve demasiado azul.'],
      { task: 'gap', say: 'Di que hay que corregir el color de este plano.', en: 'We need to [colour-correct] this shot.', es: 'Tenemos que corregir el color de este plano.' },
      ['leo', 'Right. Then add the titles and the credits.', 'Eso es. Luego añade los títulos y los créditos.'],
      { task: 'choose', say: 'Propón renderizar una previsualización para verlo.', options: [
        ["Let's render a preview.", 'Vamos a renderizar una previsualización.'],
        ["Let's render a preview it.", 'Sobra «it».'],
        ["Let's give back a preview.", '«Give back» es devolver. Renderizar se dice «render».'],
      ] },
      ['narr', 'Diez minutos después…'],
      ['leo', 'It looks great! Export a high-resolution version.', '¡Queda genial! Exporta una versión de alta resolución.'],
      { task: 'order', say: 'Di que primero harás una copia de seguridad del proyecto.', en: "I'll make a backup of the project first.", alt: ["First I'll make a backup of the project.", "I'll first make a backup of the project."], es: 'Primero haré una copia de seguridad del proyecto.' },
      ['leo', "Good idea. And please, don't overwrite the original file!", 'Buena idea. ¡Y por favor, no sobrescribas el archivo original!'],
      { task: 'choose', say: 'Dile que no se preocupe: comprobarás la exportación final.', options: [
        ["Don't worry. I'll check the final export.", 'No te preocupes. Comprobaré la exportación final.'],
        ["Don't worry. I'll checking the final export.", 'Después de «I\'ll» va el verbo sin -ing: «I\'ll check».'],
        ["Don't worry. I'll check the end export.", '«Final» es el adjetivo correcto: «final export».'],
      ] },
      ['leo', 'Great. See you tomorrow!', 'Genial. ¡Hasta mañana!'],
    ],
  },
  {
    id: 'problema', icon: '⚠️', title: '¡Problema técnico!', you: 'Ayudante de cámara',
    desc: 'La cámara se apaga en mitad del rodaje: hay que encontrar una solución.',
    cast: {
      mike: { name: 'Mike', role: 'Director de fotografía', avatar: '🧑‍🦲', pitch: 0.8 },
      emma: { name: 'Emma', role: 'Productora', avatar: '👩‍💼', pitch: 1.15 },
    },
    lines: [
      ['narr', 'Rodaje en exteriores. De repente, la cámara principal se apaga.'],
      ['mike', 'Oh no. We have a technical issue.', 'Oh, no. Tenemos un problema técnico.'],
      ['emma', "What's happening?", '¿Qué pasa?'],
      { task: 'choose', say: 'Explica que hay un problema con la cámara.', options: [
        ["There's a problem with the camera.", 'Hay un problema con la cámara.'],
        ["There's a problem in the camera with.", 'El orden no es correcto: «There\'s a problem with the camera».'],
        ['Has a problem with the camera.', 'Para decir «hay» se usa «there is / there\'s», no «has».'],
      ] },
      ['emma', 'Can we fix it?', '¿Podemos arreglarlo?'],
      { task: 'order', say: 'Di que vais a ver qué podéis hacer.', en: "Let's see what we can do.", es: 'Veamos qué podemos hacer.' },
      ['narr', 'Revisas la cámara: el cable de alimentación está roto.'],
      ['mike', 'The power cable is broken. Do we have a spare?', 'El cable de alimentación está roto. ¿Tenemos uno de repuesto?'],
      { task: 'choose', say: 'Di que no, que necesitáis uno de repuesto.', options: [
        ['No. We need a replacement.', 'No. Necesitamos un repuesto.'],
        ['No. We need a reposition.', '«Reposition» es cambiar algo de posición. Un repuesto es «a replacement» (o «a spare»).'],
        ['No. We need a substitute for replace.', 'La frase está mal construida. Se dice simplemente «We need a replacement».'],
      ] },
      ['emma', "We don't have much time. We need to find a solution.", 'No tenemos mucho tiempo. Tenemos que encontrar una solución.'],
      { task: 'choose', say: 'Pregunta si tenéis un equipo de respaldo.', options: [
        ['Do we have a backup?', '¿Tenemos un equipo de respaldo?'],
        ['Do we have a back?', '«Back» es la espalda o la parte de atrás. De respaldo es «backup».'],
        ['Have we a backup?', 'Suena muy antiguo. Hoy se pregunta con «do»: «Do we have a backup?».'],
      ] },
      ['mike', "Yes! There's a second camera in the truck.", '¡Sí! Hay una segunda cámara en el camión.'],
      ['emma', 'How long will it take to set it up?', '¿Cuánto tiempo llevará montarla?'],
      { task: 'gap', say: 'Responde que diez minutos y que hay que actuar rápido.', en: 'Ten minutes. We need to act [quickly].', es: 'Diez minutos. Tenemos que actuar rápidamente.' },
      ['narr', 'Montáis la segunda cámara, pero el monitor no da imagen.'],
      { task: 'order', say: 'Propón averiguar qué falla (solucionar el problema).', en: "Let's troubleshoot the problem.", es: 'Vamos a solucionar el problema.' },
      ['narr', 'Era el cable del monitor, que estaba suelto. Lo conectas bien y aparece la imagen.'],
      { task: 'choose', say: 'Anuncia que el problema se ha solucionado.', options: [
        ['The problem has been solved.', 'El problema se ha solucionado.'],
        ['The problem has been solve.', 'Después de «has been» va el participio: «solved».'],
        ['The problem is solutioned.', '«Solutioned» no existe. Se dice «solved».'],
      ] },
      ['emma', 'Great job! Everything is under control.', '¡Buen trabajo! Todo está bajo control.'],
    ],
  },
  {
    id: 'coordinacion', icon: '🤝', title: 'Coordinación del equipo', you: 'Jefe/a de producción',
    desc: 'Último día de rodaje: repartes tareas y lo pones todo en marcha.',
    cast: {
      sara: { name: 'Sara', role: 'Ayudante de dirección', avatar: '👩‍🦰', pitch: 1.25 },
      pablo: { name: 'Pablo', role: 'Técnico de iluminación', avatar: '👨‍🔧', pitch: 1 },
      emma: { name: 'Emma', role: 'Productora', avatar: '👩‍💼', pitch: 1.15 },
    },
    lines: [
      ['narr', 'Último día de rodaje. Tú eres el jefe de producción y hay mucho que coordinar.'],
      ['sara', "The generator for the lights isn't here yet.", 'El generador para las luces todavía no ha llegado.'],
      { task: 'choose', say: 'Tranquilízala: dile que te lo deje a ti.', options: [
        ['Leave it with me.', 'Déjamelo a mí.'],
        ['Leave me it.', 'El orden correcto es «Leave it with me».'],
        ['Let it to me.', '«Let» es dejar en el sentido de permitir. Se dice «Leave it with me».'],
      ] },
      ['narr', 'Llamas a la empresa de alquiler: el generador llegará en media hora.'],
      ['sara', "Thanks! Who's responsible for the catering?", '¡Gracias! ¿Quién es responsable del catering?'],
      { task: 'order', say: 'Di que tú te encargas.', en: "I'll take care of it.", es: 'Yo me encargo.' },
      ['pablo', "And the cables on the stairs? They're a trip hazard.", '¿Y los cables de las escaleras? Son un riesgo de tropiezo.'],
      { task: 'choose', say: 'Pídele a Pablo que se encargue él de los cables.', options: [
        ['Can you take care of this?', '¿Puedes encargarte de esto?'],
        ['Can you take care this?', 'Falta «of»: «take care of».'],
        ['Can you charge of this?', '«Be in charge of» es «estar al cargo de». Aquí se dice «take care of this».'],
      ] },
      ['pablo', "Sure. I'll sort it out.", 'Claro. Yo lo soluciono.'],
      ['emma', 'How is everything going?', '¿Cómo va todo?'],
      { task: 'gap', say: 'Dile que todo está bajo control.', en: 'Everything is under [control].', es: 'Todo está bajo control.' },
      ['emma', 'Great. We need to coordinate with the crew for tomorrow. Keep the team informed.', 'Genial. Tenemos que coordinarnos con el equipo para mañana. Mantén informado al equipo.'],
      { task: 'choose', say: 'Pide a Sara que informe al equipo.', options: [
        ['Sara, let the team know, please.', 'Sara, informa al equipo, por favor.'],
        ['Sara, let know the team, please.', 'El orden es «let the team know».'],
        ['Sara, inform to the team, please.', '«Inform» no lleva «to»: «inform the team». Lo más natural es «let the team know».'],
      ] },
      ['sara', 'Done. Everyone is on set.', 'Hecho. Todos están en el plató.'],
      { task: 'order', say: 'Pide que se aseguren de que todos estén preparados.', en: 'Make sure everyone is ready.', es: 'Asegúrate de que todos estén preparados.' },
      ['sara', "We're good to go!", '¡Estamos listos para empezar!'],
      { task: 'choose', say: '¡A rodar! Di la frase para ponerlo todo en marcha.', options: [
        ["Let's get this show on the road!", '¡Vamos a poner esto en marcha!'],
        ["Let's get this show on the street!", 'Es una expresión fija: «get the show on the road» (literalmente, «en la carretera»).'],
        ["Let's put this in march!", 'Es una traducción literal de «poner en marcha»: en inglés no tiene sentido («march» es marchar o marzo).'],
      ] },
    ],
  },
  {
    id: 'entrevista', icon: '💼', title: 'Entrevista de trabajo', you: 'Candidato/a a ayudante de producción',
    desc: 'Tu experiencia, tus soft skills y tus preguntas a la productora.',
    cast: {
      helen: { name: 'Helen', role: 'Jefa de producción', avatar: '👩‍🏫', pitch: 1.05 },
    },
    lines: [
      ['narr', 'Tienes una entrevista de trabajo para ser ayudante de producción en una productora de Londres.'],
      ['helen', 'Hello, nice to meet you. Thanks for sending your CV and your portfolio.', 'Hola, encantada. Gracias por enviar tu currículum y tu portfolio.'],
      ['helen', 'So, tell me about your work experience.', 'Bueno, háblame de tu experiencia laboral.'],
      { task: 'choose', say: 'Cuenta que hiciste unas prácticas en una serie de televisión.', options: [
        ['I did an internship on a TV series.', 'Hice unas prácticas en una serie de televisión.'],
        ['I did practices on a TV series.', '«Practices» no son prácticas de trabajo. Se dice «internship» (o «work placement»).'],
        ['I made an internship on a TV series.', 'Con «internship» se usa «do»: «I did an internship».'],
      ] },
      ['helen', 'Great. This job can be stressful. Are you good at working under pressure?', 'Genial. Este trabajo puede ser estresante. ¿Trabajas bien bajo presión?'],
      { task: 'order', say: 'Di que sí, que mantienes la calma y la concentración.', en: 'Yes, I stay calm and focused.', alt: ['Yes, I stay focused and calm.'], es: 'Sí, mantengo la calma y la concentración.' },
      ['helen', 'And what about teamwork?', '¿Y el trabajo en equipo?'],
      { task: 'choose', say: 'Di que te encanta el trabajo en equipo y que tienes buenas habilidades comunicativas.', options: [
        ['I love teamwork, and I have good communication skills.', 'Me encanta el trabajo en equipo y tengo buenas habilidades comunicativas.'],
        ['I love teamwork, and I have good communicatives skills.', 'En inglés los adjetivos no tienen plural: «communication skills» (o «communicative skills»), nunca «communicatives».'],
        ['I love work in team, and I have good communication skills.', '«Trabajo en equipo» se dice «teamwork», no «work in team».'],
      ] },
      ['helen', 'Good. Our projects are always deadline-driven. Is that a problem?', 'Bien. En nuestros proyectos siempre mandan los plazos. ¿Es un problema?'],
      { task: 'gap', say: 'Di que eres responsable y que siempre cumples los plazos.', en: "Not at all. I'm responsible and I always [meet] deadlines.", es: 'Para nada. Soy responsable y siempre cumplo los plazos.' },
      ['helen', 'Would you work freelance, or do you prefer a contract?', '¿Trabajarías como autónomo/a o prefieres un contrato?'],
      { task: 'choose', say: 'Responde que eres flexible: las dos opciones te parecen bien.', options: [
        ["I'm flexible. Both options are fine for me.", 'Soy flexible. Las dos opciones me parecen bien.'],
        ["I'm flexibility. Both options are fine for me.", '«Flexibility» es el sustantivo (flexibilidad). Para decir «soy flexible» se usa el adjetivo: «I\'m flexible».'],
        ["I'm flexible. Both options are fines for me.", 'Los adjetivos en inglés no llevan plural: «fine».'],
      ] },
      ['helen', 'Perfect. Do you have any questions?', 'Perfecto. ¿Tienes alguna pregunta?'],
      { task: 'order', say: 'Pregunta cuál es el horario laboral.', en: 'What are the working hours?', es: '¿Cuál es el horario laboral?' },
      ['helen', 'From nine to six. On shooting days, we work in shifts.', 'De nueve a seis. Los días de rodaje trabajamos por turnos.'],
      { task: 'choose', say: 'Dale las gracias por la entrevista.', options: [
        ['Thank you for your time.', 'Gracias por su tiempo.'],
        ['Thank you for your hour.', '«Hour» es una hora del reloj. Se dice «Thank you for your time».'],
        ['Thanks you for your time.', 'Es «Thank you» o «Thanks», pero no «Thanks you».'],
      ] },
      ['helen', "Thank you. We'll get back to you next week.", 'Gracias. Nos pondremos en contacto contigo la semana que viene.'],
      ['narr', 'Una semana después te llega un correo: ¡el trabajo es tuyo! 🎉'],
    ],
  },
];
